baseURL = "https://yzwer.github.io/"
languageCode = "zh-CN"
title = "Zwer's Home"
theme = "LoveIt"
enableEmoji = true
hasCJKLanguage = true

[params.author]
  name = "zwer"
  email = "yzwer@qq.com"
  link = "https://yzwer.github.io/"

[params]
  version = "0.2.9"
  description = "Zwer的个人网站"
  since = "2019"
  title = "Zwer's Home"
  subtitle = "工作 生活 兴趣 感悟.."
  keywords = ["zwer", "blog", "个人网站"]
  headerTitle = "Zwer's Home"
  pageStyle = "wide"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params.search]
  enable = false

[params.comment]
  [params.comment.valine]
    enable = true
    appId = "l6jCjqeyLVrAi7qY4I1MGcLp-gzGzoHsz"
    appKey = "PkBxKrc6OrzJrOIY1k7JyVSA"
    avatar = "mm"
    placeholder = "说点什么吧.."
    visitor = true
    recordIP = true
    enableQQ = false

[params.license]
  enable = true
  content = 'This work is licensed under a <a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>.'

[params.assets]
  disableFancybox = true
  disableScrollbar = true

[params.analysis]
  enable = false

[params.pwa]
  enable = false
